### ISSUE TITLE
貌似本地不能运行了

### ISSUE THREAD

**Issue by ithack** [microzz/vue-chat#1]
window 本地之行顺序如下：
npm install => npm run dev 
报错：

> Starting dev server...
 ERROR  Failed to compile with 5 errors10:04:28

 error  in ./src/App.vue

Module build failed: Error: %1 is not a valid Win32 application.
\\?\E:\前端测试dome\vue-chat\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-2a75fd14","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-367 13:3-17:5 14:22-375
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Login/Login.vue

Module build failed: Error: %1 is not a valid Win32 application.
\\?\E:\前端测试dome\vue-chat\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-31773447","scoped":true,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Login/Login.vue 4:14-392 13:3-17:5 14:22-400
 @ ./src/components/Login/Login.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Chatting/Chatting.vue

Module build failed: Error: %1 is not a valid Win32 application.
\\?\E:\前端测试dome\vue-chat\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-05b45833","scoped":true,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Chatting/Chatting.vue 4:14-395 13:3-17:5 14:22-403
 @ ./src/components/Chatting/Chatting.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Chatting/AI.vue

Module build failed: Error: %1 is not a valid Win32 application.
\\?\E:\前端测试dome\vue-chat\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-08a4dcb5","scoped":true,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Chatting/AI.vue 4:14-389 13:3-17:5 14:22-397
 @ ./src/components/Chatting/AI.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/About/About.vue

Module build failed: Error: %1 is not a valid Win32 application.
\\?\E:\前端测试dome\vue-chat\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (E:\前端测试dome\vue-chat\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-412f0d8f","scoped":true,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/About/About.vue 4:14-392 13:3-17:5 14:22-400
 @ ./src/components/About/About.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Login/Login.vue
 @ ./src/components/Login/Login.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

是需要安装什么其他环境吗？

**Comment by microzz** [comment]
@ithack 你好，升级到最新node，cd到项目下安装所有依赖，建议翻墙或者使用cnpm

**Comment by ithack** [comment]
@microzz 
```
$ node -v
v6.10.0
```
依赖包肯定都装了，总感觉scss解析不了，但是依赖包已经下了啊，你的是node几

**Comment by microzz** [comment]
@ithack sass经常安装不了，推荐翻墙或者cnpm

**Comment by ithack** [comment]
@microzz 我npm默认就是镜像上拉东西啊！

**Comment by ithack** [comment]
@microzz 把依赖删了，重新install一下好了
